// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo-service.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	todo-service.proto

It has these top-level messages:
	Evento
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	ReadAllRequest
	ReadAllResponse
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Taks we have to do
type Evento struct {
	// Unique integer identifier of the todo task
	IdEvento int64 `protobuf:"varint,1,opt,name=id_evento,json=idEvento" json:"id_evento,omitempty"`
	// Title of the task
	Nombre string `protobuf:"bytes,2,opt,name=nombre" json:"nombre,omitempty"`
	// Detail description of the todo task
	Tipo string `protobuf:"bytes,3,opt,name=tipo" json:"tipo,omitempty"`
	// Detail description of the todo task
	IdVenue string `protobuf:"bytes,4,opt,name=id_venue,json=idVenue" json:"id_venue,omitempty"`
	// Date and time to remind the todo task
	Fecha string `protobuf:"bytes,5,opt,name=fecha" json:"fecha,omitempty"`
	Hora  string `protobuf:"bytes,6,opt,name=hora" json:"hora,omitempty"`
}

func (m *Evento) Reset()                    { *m = Evento{} }
func (m *Evento) String() string            { return proto.CompactTextString(m) }
func (*Evento) ProtoMessage()               {}
func (*Evento) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Evento) GetIdEvento() int64 {
	if m != nil {
		return m.IdEvento
	}
	return 0
}

func (m *Evento) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *Evento) GetTipo() string {
	if m != nil {
		return m.Tipo
	}
	return ""
}

func (m *Evento) GetIdVenue() string {
	if m != nil {
		return m.IdVenue
	}
	return ""
}

func (m *Evento) GetFecha() string {
	if m != nil {
		return m.Fecha
	}
	return ""
}

func (m *Evento) GetHora() string {
	if m != nil {
		return m.Hora
	}
	return ""
}

// Request data to create new todo task
type CreateRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Task entity to add
	Evento *Evento `protobuf:"bytes,2,opt,name=evento" json:"evento,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetEvento() *Evento {
	if m != nil {
		return m.Evento
	}
	return nil
}

// Contains data of created todo task
type CreateResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// ID of created task
	IdEvento int64 `protobuf:"varint,2,opt,name=id_evento,json=idEvento" json:"id_evento,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetIdEvento() int64 {
	if m != nil {
		return m.IdEvento
	}
	return 0
}

// Request data to read todo task
type ReadRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Unique integer identifier of the todo task
	IdEvento int64 `protobuf:"varint,2,opt,name=id_evento,json=idEvento" json:"id_evento,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadRequest) GetIdEvento() int64 {
	if m != nil {
		return m.IdEvento
	}
	return 0
}

// Contains todo task data specified in by ID request
type ReadResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Task entity read by ID
	Evento *Evento `protobuf:"bytes,2,opt,name=evento" json:"evento,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadResponse) GetEvento() *Evento {
	if m != nil {
		return m.Evento
	}
	return nil
}

// Request data to read all todo task
type ReadAllRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
}

func (m *ReadAllRequest) Reset()                    { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()               {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

// Contains list of all todo tasks
type ReadAllResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// List of all todo tasks
	Eventos []*Evento `protobuf:"bytes,2,rep,name=eventos" json:"eventos,omitempty"`
}

func (m *ReadAllResponse) Reset()                    { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()               {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadAllResponse) GetEventos() []*Evento {
	if m != nil {
		return m.Eventos
	}
	return nil
}

func init() {
	proto.RegisterType((*Evento)(nil), "v1.Evento")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "v1.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "v1.ReadResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "v1.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "v1.ReadAllResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ToDoService service

type ToDoServiceClient interface {
	// Create new todo task
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Read todo task
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Read all todo tasks
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
}

type toDoServiceClient struct {
	cc *grpc.ClientConn
}

func NewToDoServiceClient(cc *grpc.ClientConn) ToDoServiceClient {
	return &toDoServiceClient{cc}
}

func (c *toDoServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/v1.ToDoService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/v1.ToDoService/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := grpc.Invoke(ctx, "/v1.ToDoService/ReadAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ToDoService service

type ToDoServiceServer interface {
	// Create new todo task
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// Read todo task
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// Read all todo tasks
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
}

func RegisterToDoServiceServer(s *grpc.Server, srv ToDoServiceServer) {
	s.RegisterService(&_ToDoService_serviceDesc, srv)
}

func _ToDoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToDoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ToDoService",
	HandlerType: (*ToDoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ToDoService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ToDoService_Read_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _ToDoService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo-service.proto",
}

func init() { proto.RegisterFile("todo-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x4d, 0x5b, 0x28, 0x30, 0x28, 0xe0, 0x68, 0xcc, 0x8a, 0x17, 0xb2, 0xf1, 0x80, 0x07, 0x31,
	0xe0, 0xd5, 0xc4, 0x18, 0xe1, 0xe0, 0xb5, 0x1a, 0xaf, 0xa4, 0xd0, 0x31, 0x6c, 0x82, 0xdd, 0xda,
	0x96, 0xfe, 0x14, 0x6f, 0xfe, 0x57, 0xb3, 0x1f, 0x08, 0x35, 0xd6, 0x78, 0x9b, 0x79, 0x6f, 0xe6,
	0xcd, 0x9b, 0xdd, 0x01, 0xcc, 0x65, 0x24, 0xaf, 0x32, 0x4a, 0x0b, 0xb1, 0xa4, 0x51, 0x92, 0xca,
	0x5c, 0xa2, 0x5b, 0x8c, 0xf9, 0x87, 0x03, 0xfe, 0xac, 0xa0, 0x38, 0x97, 0x78, 0x0e, 0x2d, 0x11,
	0xcd, 0x49, 0x27, 0xcc, 0x19, 0x38, 0x43, 0x2f, 0x68, 0x8a, 0xc8, 0x92, 0xa7, 0xe0, 0xc7, 0xf2,
	0x6d, 0x91, 0x12, 0x73, 0x07, 0xce, 0xb0, 0x15, 0xd8, 0x0c, 0x11, 0x6a, 0xb9, 0x48, 0x24, 0xf3,
	0x34, 0xaa, 0x63, 0x3c, 0x83, 0xa6, 0x88, 0xe6, 0x05, 0xc5, 0x1b, 0x62, 0x35, 0x8d, 0x37, 0x44,
	0xf4, 0xa2, 0x52, 0x3c, 0x81, 0xfa, 0x2b, 0x2d, 0x57, 0x21, 0xab, 0x6b, 0xdc, 0x24, 0x4a, 0x64,
	0x25, 0xd3, 0x90, 0xf9, 0x46, 0x44, 0xc5, 0x7c, 0x06, 0x87, 0x0f, 0x29, 0x85, 0x39, 0x05, 0xf4,
	0xbe, 0xa1, 0x2c, 0xc7, 0x1e, 0x78, 0x61, 0x22, 0xb4, 0xb1, 0x56, 0xa0, 0x42, 0xe4, 0xe0, 0x5b,
	0xb7, 0xca, 0x53, 0x7b, 0x02, 0xa3, 0x62, 0x3c, 0x32, 0x7e, 0x03, 0xcb, 0xf0, 0x3b, 0xe8, 0x6c,
	0x65, 0xb2, 0x44, 0xc6, 0x19, 0xfd, 0xa2, 0x53, 0x5a, 0xdc, 0x2d, 0x2f, 0xce, 0x6f, 0xa1, 0x1d,
	0x50, 0x18, 0x55, 0xbb, 0xf8, 0xb3, 0x7b, 0x0a, 0x07, 0xa6, 0xbb, 0x72, 0xf8, 0x7f, 0x96, 0xe0,
	0xd0, 0x51, 0x2a, 0xf7, 0xeb, 0x75, 0xa5, 0x0d, 0xfe, 0x08, 0xdd, 0xef, 0x9a, 0xca, 0x61, 0x17,
	0xd0, 0x30, 0x92, 0x19, 0x73, 0x07, 0xde, 0x8f, 0x69, 0x5b, 0x6a, 0xf2, 0xe9, 0x40, 0xfb, 0x59,
	0x4e, 0xe5, 0x93, 0xb9, 0x16, 0xbc, 0x06, 0xdf, 0xbc, 0x21, 0x1e, 0xa9, 0xf2, 0xd2, 0xb7, 0xf4,
	0x71, 0x1f, 0xb2, 0x83, 0x2f, 0xa1, 0xa6, 0xbc, 0x60, 0x57, 0x71, 0x7b, 0xaf, 0xd7, 0xef, 0xed,
	0x00, 0x5b, 0x3a, 0x81, 0x86, 0xb5, 0x8d, 0xb8, 0x25, 0x77, 0x7b, 0xf6, 0x8f, 0x4b, 0x98, 0xe9,
	0x59, 0xf8, 0xfa, 0x7c, 0x6f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x41, 0xe7, 0x6d, 0xda, 0xd4,
	0x02, 0x00, 0x00,
}
